### ISSUE TITLE
Add automatic Install (Add-On) System for JARVIS

### ISSUE THREAD

**Issue by Namiabi** [TheLeCraft999/jarvis#10]

**Comment by TheLeCraft999** [comment]
Could you please explain what exactly you mean with that?

**Comment by Namiabi** [comment]
You can choose inside of JARVIS (or the installer) what "addons" you want to add. In my opinion that complete addon system is weird and i dont like it. I mean why dont integrate all of the commands in JARVIS and then add a clear help command.

**Comment by TheLeCraft999** [comment]
That was the idea previously, but then we started working on commands, that would require more space and decided, the user schould decide what he wants or needs. We are working on a download system via the website, so stay tuned.
Thank you
