### ISSUE TITLE
Rework Installer Interface/GUI

### ISSUE THREAD

**Issue by Namiabi** [TheLeCraft999/jarvis#7]
-More Minimalistic
-White Mode (or Dark?)
-Language changer (DE/EN)
_-Rework of the TOS/EULA_
-Instead of pressing "Install and accept[the TOS/EULA]" a checkbox for the TOS/EULA, you can only further install JARVIS if you checked the checkbox
-(AUTOMATIC) DOWNLOAD LINK FOR THE INTRODUCTION PFD
-Add "Time left" for the Installer
-Jarvis opens automatic after installation
-Installer closes after 10 seconds of the installation of Jarvis

**Comment by TheLeCraft999** [comment]
We are already on a more minimalistic design and on a white-mode installer. Unfortunately we are currently not trying to implement multible languages. We are working on the rest and in one of the next updates it will be fixed.
